# Codex autonomous-profile renderer
#
# Pure function producing the Codex config files baked into agent container
# images. Deliberately NOT a home-manager module: there must be no code path
# that renders these onto a host filesystem. Safety in this profile comes from
# the container boundary, scoped credentials, and default-deny egress.
#
# Codex uses native config.toml keys for sandbox/approval defaults and an
# execpolicy `.rules` file for command-prefix decisions outside the sandbox.
#
# `residualDeny` is the caller's list of command prefixes that must stay denied
# even under a bypass posture — operations reachable through the agent's
# *credentials* rather than the filesystem (repo deletion, secret mutation,
# force-push, registry publish).
{
  lib,
  # Accepted for signature parity with the other per-tool renderers; Codex
  # writes only home-relative paths, so it needs no absolute home directory.
  homeDir ? "/home/agent",
  residualDeny,
}:

let
  tokenizeCommand = cmd: lib.filter (token: token != "") (lib.splitString " " cmd);

  # Codex execpolicy prefix_rule matches literal argv tokens, so a command
  # carrying shell metacharacters or globs cannot be expressed at all. Such
  # entries are dropped rather than mangled into a rule that would match the
  # wrong thing; the count is reported in the file header.
  tokenIsRepresentable =
    token:
    !(lib.any (char: lib.hasInfix char token) [
      "*"
      "?"
      "<"
      ">"
      "|"
      "&"
      ";"
      "$"
      "("
      ")"
      "{"
      "}"
      "\""
      "'"
      "\\"
      "`"
      "~"
    ]);

  commandIsRepresentable =
    cmd:
    let
      tokens = tokenizeCommand cmd;
    in
    tokens != [ ] && lib.all tokenIsRepresentable tokens;

  supportedCommands = cmds: lib.filter commandIsRepresentable cmds;

  skippedCommands =
    cmds: builtins.length cmds - builtins.length (supportedCommands cmds);

  formatPrefixRule =
    decision: cmd: "prefix_rule(${builtins.toJSON (tokenizeCommand cmd)}, ${builtins.toJSON decision})";

  renderRules =
    decision: cmds: lib.concatMapStringsSep "\n" (formatPrefixRule decision) (supportedCommands cmds);

  # Header text is byte-identical to the nix-ai render this repo took over, so
  # image builds can be diffed across the move.
  formatRulesFile =
    permissions:
    let
      skippedTotal =
        skippedCommands permissions.allow
        + skippedCommands permissions.ask
        + skippedCommands permissions.deny;
    in
    ''
      # Generated by nix-ai from ai-assistant-instructions/agentsmd/permissions/.
      # These rules apply to commands outside Codex's filesystem sandbox.
      # Unsupported shell-only patterns were skipped: ${toString skippedTotal}

      ${renderRules "forbidden" permissions.deny}

      ${renderRules "prompt" permissions.ask}

      ${renderRules "allow" permissions.allow}
    '';

  permissions = {
    allow = [ ];
    ask = [ ];
    deny = residualDeny;
  };

  # ~/.codex/config.toml inside the image. Launched as `codex exec`.
  # danger-full-access is correct, not careless: bwrap cannot nest inside an
  # unprivileged container, and the container is the sandbox.
  configToml = ''
    # Generated by nix-ai (autonomous profile). Do not use on a host:
    # this configuration assumes a container is the isolation boundary.
    approval_policy = "never"
    sandbox_mode = "danger-full-access"
  '';

  rules = formatRulesFile permissions;
in
{
  inherit
    homeDir
    residualDeny
    configToml
    rules
    commandIsRepresentable
    supportedCommands
    ;

  # Home-relative path -> contents, ready for an image builder to bake under
  # homeDir. One attrset so image builds cannot forget a file.
  files = {
    ".codex/config.toml" = configToml;
    ".codex/rules/default.rules" = rules;
  };
}
