name: Nix CI

on:
  pull_request:
  push:
    branches: [develop, main]

permissions:
  contents: read

jobs:
  linux:
    uses: dryvist/.github/.github/workflows/_nix-validate.yml@8b2ab29ff2a86547cefab11913d737f1062b1a7c # main
    with:
      runner_label: ubuntu-latest
      all_systems: false

  macos:
    needs: linux
    uses: dryvist/.github/.github/workflows/_nix-validate.yml@8b2ab29ff2a86547cefab11913d737f1062b1a7c # main
    with:
      runner_label: macos-latest
      all_systems: false
