name: Nix CI

on:
  pull_request:
  push:
    branches: [develop, main]

permissions:
  contents: read

jobs:
  linux:
    uses: dryvist/.github/.github/workflows/_nix-validate.yml@c4501ea67ce4469a5cc95216c9a989516da2adb8 # v1.10.0
    with:
      runner_label: ubuntu-latest
      all_systems: false

  macos:
    needs: linux
    uses: dryvist/.github/.github/workflows/_nix-validate.yml@c4501ea67ce4469a5cc95216c9a989516da2adb8 # v1.10.0
    with:
      runner_label: macos-latest
      all_systems: false
